//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.07 at 02:19:19 PM CEST 
//


package de.hpi.ingest.model.diagram;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import org.oryxeditor.server.diagram.Shape;

import de.hpi.ingest.model.connector.SequenceFlow;




@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class SequenceFlowConnector
    extends IngestConnector
{

    @XmlAttribute
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected SequenceFlow sequenceFlowRef;
    
    /**
     * Adds sequence flow specific attributes to the JSON representation.
     */
    public Shape toShape() {
    	Shape shape = super.toShape();
    	this.getSequenceFlowRef().toShape(shape);
    	return shape;
    }
    
    /* Getter & Setter */
    
    /**
     * Gets the value of the sequenceFlowRef property.
     * 
     * @return
     *     possible object is
     *     {@link SequenceFlow }
     *     
     */
    public SequenceFlow getSequenceFlowRef() {
        return sequenceFlowRef;
    }

    /**
     * Sets the value of the sequenceFlowRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequenceFlow }
     *     
     */
    public void setSequenceFlowRef(SequenceFlow value) {
        this.sequenceFlowRef = value;
    }

}
